### PR TITLE
Remove README and LICENSE

### PR DESCRIPTION
**Pull request by nikhita**
Addresses https://github.com/kubernetes/kubernetes/issues/54398.

/cc @sttts @munnerz

### CODE REVIEW

**Comment by munnerz** [comment]
Not sure how to trigger merges on this repo.. I guess because we haven't synced OWNERS yet, nobody is an owner?

**Comment by nikhita** [comment]
> I guess because we haven't synced OWNERS yet, nobody is an owner?

Yeah, mostly only the people with write access can merge it.

**Comment by sttts** [comment]
I would prefer to slowly switch to have these files in the staging repo. For sample-apiserver this is already the case. In other words, instead of extending the files here, we have to delete them. The sync will bring them back.

**Comment by nikhita** [comment]
> In other words, instead of extending the files here, we have to delete them.

Do you want me to delete the files in this PR then? Or just let it be how it is for now?

**Comment by sttts** [comment]
> Do you want me to delete the files in this PR then? Or just let it be how it is for now?

Would be good. We should do that for all repos but client-go.

**Comment by nikhita** [comment]
@sttts Updated to remove the files.

**Pull request merged**
